config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    member do
      get :follows, :followers
    end
    resource :relationships, only: %i[create destroy]
  end

  devise_scope :user do
    get 'users/auth/:provider/callback', to: 'users/omniauth_callbacks#github'
  end

  root to: 'tweets#index'
  resources :tweets do
    collection do
      get 'bookmarks', to: 'tweets#bookmarks'
    end
    resources :comments, only: [:create]
    resource :favorites, only: %i[create destroy]
    resource :retweets, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end

  post '/tweets', to: 'tweets#create'

  resources :rooms

  resources :rooms do
    resources :messages
  end

  resources :notifications, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140 }, unless: proc { image.attached? }

  has_many :retweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many_attached :image

  has_one :notification, as: :subject, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def retweeted_by?(user)
    retweets.exists?(user_id: user.id)
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end
end

app/controllers/Tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  def index
    return if current_user.blank?

    @tweets = Tweet.all.order(created_at: 'DESC').page(params[:page]).per(5)
    @user = current_user
    following_user_id = @user.following_user.ids
    @follower_tweets = Tweet.where(user_id: following_user_id).order(created_at: 'DESC').page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = current_user.tweets.build(tweet_params)
    if tweet.save
      redirect_to tweets_path, notice: 'ツイートを作成しました。'
    elsif tweet.content == ''
      redirect_to tweets_path, alert: 'ツイートまたは画像がありません。'
    else
      redirect_to tweets_path, alert: 'ツイートの投稿に失敗しました。'
    end
  end

  def show
    return if current_user.blank?

    @tweets = Tweet.all.order(created_at: 'DESC').page(params[:page]).per(5)
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @user = current_user
    @favorites = @user.favorites.order(created_at: 'DESC')
    @retweets = @user.retweets.order(created_at: 'DESC')
    @comments = @user.comments.order(created_at: 'DESC')
  end

  def bookmarks
    return if current_user.blank?

    @user = current_user
    @bookmarks = @user.bookmarks.order(created_at: 'DESC')
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, image: [])
  end
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/views/tweets/bookmarks.html.slim
doctype html
html[lang="ja"]
  head
    meta[charset="utf-8"]
    title
      | Twitterクローン
    link href="/assets/bookmark.css" rel="stylesheet"

  body 
    = render partial: 'shared/header'    
    .border-top.mt-3
      - if user_signed_in?
        .container
          .row
            .col-2
              .mt-3
                = button_to root_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-house-door
                  | &nbsp;&nbsp;ホーム
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-hash
                  | &nbsp;&nbsp;話題を検索
              .mt-3
                = button_to notifications_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bell
                  | &nbsp;&nbsp;通知
              .mt-3
                = button_to rooms_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-envelope
                  | &nbsp;&nbsp;メッセージ
              .mt-3
                = button_to bookmarks_tweets_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  strong
                    i.bi.bi-bookmark-fill
                    | &nbsp;&nbsp;ブックマーク
              .mt-3
                = button_to user_path(@user), method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-person
                  | &nbsp;&nbsp;プロフィール
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-three-dots
                  | &nbsp;&nbsp;もっと見る
              .mt-3
                button.btn.btn-primary.col-11.tweet_button
                  | ツイートする
              .side_user_icon
                .d-flex.align-items-center
                  - if current_user.avatar.attached?
                    = image_tag current_user.avatar, size: '50x50'
                  - else
                    = image_tag 'default_user.PNG', size: '50x50'
                  .d-flex.flex-column.side_user_name
                    strong = current_user.name
                    = "@" + current_user.custom_user_id

            .col-8.main_before_login
              - if @bookmarks.present?
                - @bookmarks.each do |bookmark|
                  .container.d-flex.pt-2
                    .avatar
                      - if bookmark.tweet.user.avatar.attached? 
                        = link_to user_path(bookmark.tweet.user.id) do
                          .avatar = image_tag bookmark.tweet.user.avatar, size: '50x50'
                      - else
                        = link_to user_path(bookmark.tweet.user.id) do
                          .avatar = image_tag 'default_user.PNG', size: '50x50'
                    .user.d-flex.flex-row.ms-2
                      strong = bookmark.tweet.user.name
                      .ms-2.custom-user-id= " @" + bookmark.tweet.user.custom_user_id
                    .follow_button.ms-auto
                      = render partial: 'shared/follow_button', locals: { tweet: bookmark }
                      br
                  .tweet.d-flex.flex-column
                    = link_to tweet_path(bookmark.tweet.id), class: "text-decoration-none text-dark " do
                      = bookmark.tweet.content
                      - if bookmark.tweet.image.attached?
                          - if bookmark.tweet.image.length == 1
                            .row
                              .col-md-10
                                .d-flex.tweet_image.mt-2
                                  = image_tag bookmark.tweet.image.first, size: '600x400'
                          - else
                            .row
                              - tweet.image.each do |image|
                                .col-md-5
                                  .d-flex.tweet_image.mt-2
                                    = image_tag image, size: '300x200'
                      .container.mt-2.d-flex.justify-content-between
                        button.btn-light.mt-2.tweet_form_icon
                          i.bi.bi-chat
                        = render partial: 'retweets/retweet_button', locals: { tweet: bookmark.tweet }
                        = render partial: 'favorites/favorite_buttom', locals: { tweet: bookmark.tweet }
                        = render partial: 'bookmarks/bookmark_button', locals: { tweet: bookmark.tweet }
                        button.btn-light.mt-2.tweet_form_icon
                          i.bi.bi-upload
                  .border-bottom
              - else
                  h2.fw-bold.text-center.pt-4
                      | ブックマークしているツイートがありません。
    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"




    
    

app/views/tweets/index.html.slim
doctype html
html[lang="ja"]
  head
    meta[charset="utf-8"]
    title
      | Twitterクローン
    link href="/assets/index.css" rel="stylesheet"

  body
    = render partial: 'shared/header'    
    .border-top.mt-3
      - if user_signed_in?
        .container
          .row
            .col-2
              .mt-3
                = button_to root_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  strong
                    i.bi.bi-house-door-fill
                    | &nbsp;&nbsp;ホーム
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-hash
                  | &nbsp;&nbsp;話題を検索
              .mt-3
                = button_to notifications_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bell
                  | &nbsp;&nbsp;通知
              .mt-3
                = button_to rooms_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-envelope
                  | &nbsp;&nbsp;メッセージ
              .mt-3
                = button_to bookmarks_tweets_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bookmark
                  | &nbsp;&nbsp;ブックマーク
              .mt-3
                = button_to user_path(@user), method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-person
                  | &nbsp;&nbsp;プロフィール
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-three-dots
                  | &nbsp;&nbsp;もっと見る
              .mt-3
                button.btn.btn-primary.col-11.tweet_button
                  | ツイートする
              .side_user_icon
                .d-flex.align-items-center
                  - if current_user.avatar.attached?
                    = image_tag current_user.avatar, size: '50x50'
                  - else
                    = image_tag 'default_user.PNG', size: '50x50'
                  .d-flex.flex-column.side_user_name
                    strong = current_user.name
                    = "@" + current_user.custom_user_id
                
            .col-8.main_before_login
              .tabs
                ul.nav.nav-tabs.nav-justified
                  li.nav-item
                    a.nav-link.active(data-toggle="tab" href="#section1") おすすめ
                  li.nav-item
                    a.nav-link(data-toggle="tab" href="#section2") フォロー中
                .container.d-flex.justify-content-between.border-bottom
                  .user_icon.mt-3
                    - if current_user.avatar.attached?
                      = link_to user_path(@user) do
                        = image_tag current_user.avatar, size: '50x50'
                    - else
                      = link_to user_path(@user) do
                        = image_tag 'default_user.PNG', size: '50x50'
                  .tweet_form.mt-3
                    = form_with model: Tweet.new, url: '/tweets', local:true, data: { turbo: false } do |f| 
                      .form-group
                        = f.text_area :content, class: 'form-control', placeholder: 'いまどうしてる？'
                      .mt-2.d-flex.justify-content-between
                        .btn-primary.picture_icon = f.label :image do
                          i.bi.bi-image[style="cursor: pointer"]
                          = f.file_field :image, style: "display: none", multiple: true
                        .form-group
                          = f.submit 'ツイートする', class: 'btn btn-primary tweet_button'
                          .mt-1

                .tab-content
                  #section1.tab-pane.fade.show.active.mt-2
                    - @tweets.each do |tweet|
                      .container.d-flex.mt-2
                        .avatar
                          - if tweet.user.avatar.attached? 
                            = link_to user_path(tweet.user.id) do
                              .avatar = image_tag tweet.user.avatar, size: '50x50'
                          - else
                            = link_to user_path(tweet.user.id) do
                              .avatar = image_tag 'default_user.PNG', size: '50x50'
                        .user.d-flex.flex-row.ms-2
                          strong = tweet.user.name
                          .ms-2.custom-user-id= " @" + tweet.user.custom_user_id
                        .follow_button.ms-auto
                          = render partial: 'shared/follow_button', locals: { tweet: tweet }
                      .tweet
                        = link_to tweet_path(tweet.id), class: "text-decoration-none text-dark " do
                          = tweet.content
                          - if tweet.image.attached?
                              - if tweet.image.length == 1
                                .row
                                  .col-md-10
                                    .d-flex.tweet_image.mt-2
                                      = image_tag tweet.image.first, size: '600x400'
                              - else
                                .row
                                  - tweet.image.each do |image|
                                    .col-md-5
                                      .d-flex.tweet_image.mt-2
                                        = image_tag image, size: '300x200'
                          .container.mt-2.d-flex.justify-content-between
                            button.btn-light.mt-2.tweet_form_icon
                              i.bi.bi-chat
                            = render partial: 'retweets/retweet_button', locals: { tweet: tweet }
                            = render partial: 'favorites/favorite_buttom', locals: { tweet: tweet }
                            = render partial: 'bookmarks/bookmark_button', locals: { tweet: tweet }
                            button.btn-light.mt-2.tweet_form_icon
                              i.bi.bi-upload
                      .mt-2.border-bottom
                    = paginate @tweets

                  #section2.tab-pane.fade
                    - @follower_tweets.each do |tweet|
                      .container.d-flex.mt-2
                        .avatar
                          - if tweet.user.avatar.attached? 
                            = link_to user_path(tweet.user.id) do
                              .avatar = image_tag tweet.user.avatar, size: '50x50'
                          - else
                            = link_to user_path(tweet.user.id) do
                              .avatar = image_tag 'default_user.PNG', size: '50x50'
                        .user.d-flex.flex-row.ms-2
                          strong = tweet.user.name
                          .ms-2.custom-user-id= " @" + tweet.user.custom_user_id
                        .follow_button.ms-auto
                          = render partial: 'shared/follow_button', locals: { tweet: tweet }
                          br
                      .tweet.d-flex.flex-column
                        = link_to tweet_path(tweet.id), class: "text-decoration-none text-dark " do
                          = tweet.content
                          - if tweet.image.attached?
                              - if tweet.image.length == 1
                                .row
                                  .col-md-10
                                    .d-flex.tweet_image.mt-2
                                      = image_tag tweet.image.first, size: '600x400'
                              - else
                                .row
                                  - tweet.image.each do |image|
                                    .col-md-5
                                      .d-flex.tweet_image.mt-2
                                        = image_tag image, size: '300x200'
                          .container.mt-2.d-flex.justify-content-between
                            button.btn-light.mt-2.tweet_form_icon
                              i.bi.bi-chat
                            = render partial: 'retweets/retweet_button', locals: { tweet: tweet }
                            = render partial: 'favorites/favorite_buttom', locals: { tweet: tweet }
                            button.btn-light.mt-2.tweet_form_icon
                              i.bi.bi-bookmark
                            button.btn-light.mt-2.tweet_form_icon
                              i.bi.bi-upload
                      .mt-2.border-bottom
                    = paginate @follower_tweets

      - else
        .container
          .row
            .col-3.border-end
              .mt-3
                button.btn.btn-light.side_menu
                  | <i class='bi bi-hash'></i>&nbsp;&nbsp;話題を検索
              .mt-3
                button.btn.btn-light.side_menu
                  | <i class="bi bi-gear"></i>&nbsp;&nbsp;設定
            .col-8.main_before_login
              .mt-3.fw-bold
                | Twitterを使ってみよう
              .mt-2.fw-lighter
                | 今すぐ登録して、タイムラインをカスタマイズしましょう。
              .mt-2
                = link_to "アカウントを作成", new_user_registration_path, class: "btn btn-outline-dark main_before_login_button"


    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"




    

app/views/tweets/show.html.slim
doctype html
html[lang="ja"]
  head
    meta[charset="utf-8"]
    title
      | Twitterクローン
    link href="/assets/tweet_show.css" rel="stylesheet"

  body
    = render partial: 'shared/header'
    .border-top.mt-3
      - if user_signed_in?
        .container
          .row
            .col-2
              .mt-3
                = button_to root_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-house-door
                  | &nbsp;&nbsp;ホーム
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-hash
                  | &nbsp;&nbsp;話題を検索
              .mt-3
                = button_to notifications_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bell
                  | &nbsp;&nbsp;通知
              .mt-3
                = button_to rooms_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-envelope
                  | &nbsp;&nbsp;メッセージ
              .mt-3
                = button_to bookmarks_tweets_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bookmark
                  | &nbsp;&nbsp;ブックマーク
              .mt-3
                = button_to user_path(@user), method: :get, class: "btn btn-light side_menu profile_button" do
                    i.bi.bi-person-fill
                    | &nbsp;&nbsp;プロフィール
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-three-dots
                  | &nbsp;&nbsp;もっと見る
              .mt-3
                button.btn.btn-primary.col-11.tweet_button
                  | ツイートする
              .side_user_icon
                .d-flex.align-items-center
                  - if current_user.avatar.attached?
                    .avatar = image_tag current_user.avatar, size: '50x50'
                  - else
                    .avatar = image_tag 'default_user.PNG', size: '50x50'
                  .d-flex.flex-column.side_user_name
                    strong = current_user.name
                    = "@" + current_user.custom_user_id

            .col-8.main_before_login
              .container.d-flex.pt-2
                .user_icon
                  - if @tweet.user.avatar.attached? 
                    = link_to user_path(@tweet.user.id) do
                      .avatar = image_tag @tweet.user.avatar, size: '50x50'
                  - else
                    = link_to user_path(@tweet.user.id) do
                      .avatar = image_tag 'default_user.PNG', size: '50x50'
                .user.d-flex.flex-column.ms-2
                  strong = @tweet.user.name
                  span.custom-user-id= " @" + @tweet.user.custom_user_id
                .follow_button.ms-auto
                  = render partial: 'shared/follow_button', locals: { tweet: @tweet }
              .tweet.pb-2
                = link_to tweet_path(@tweet.id), class: "text-decoration-none text-dark" do
                  = @tweet.content
                  - if @tweet.image.attached?
                    - if @tweet.image.length == 1
                      .row
                        .col-md-12
                          .d-flex.tweet_image.mt-2
                            = image_tag @tweet.image.first, size: '600x400'
                    - else
                      .row
                        - @tweet.image.each do |image|
                          .col-md-6
                            .d-flex.tweet_image.mt-2
                              = image_tag image, size: '300x200'
              .container.form_icon
                .tweet_detail_form_icon.pb-2.border-top.border-bottom.d-flex.justify-content-between
                  button.btn-light.mt-2.tweet_form_icon
                    i.bi.bi-chat
                  = render partial: 'retweets/retweet_button', locals: { tweet: @tweet }
                  = render partial: 'favorites/favorite_buttom', locals: { tweet: @tweet }
                  = render partial: 'bookmarks/bookmark_button', locals: { tweet: @tweet }
                  button.btn-light.mt-2.tweet_form_icon
                    i.bi.bi-upload
                
              .container.d-flex.justify-content-between.border-bottom
                .user_icon.mt-3
                  - if current_user.avatar.attached?
                    = link_to user_path(current_user) do
                      = image_tag current_user.avatar, size: '50x50'
                  - else
                    = link_to user_path(current_user) do
                      = image_tag 'default_user.PNG', size: '50x50'
                .tweet_form.mt-3
                  = form_with model: [@tweet, @comment], local:true, data: { turbo: false } do |f| 
                    .form-group
                      = f.text_area :content, class: 'form-control', placeholder: '返信をツイート'
                    .mt-2.d-flex.justify-content-between
                      .btn-primary.comment_form_icon = f.label :image do
                        i.bi.bi-image[style="cursor: pointer"]
                        = f.file_field :image, style: "display: none", multiple: true
                      .form-group
                        = f.submit '返信', class: 'btn btn-primary tweet_button'
                        .mt-1
              .comments
                - @tweet.comments.each do |comment|
                  .container.d-flex.flex-row.align-items-start.pt-2
                    - if comment.user.avatar.attached? 
                      = link_to user_path(comment.user.id) do
                        .user_icon = image_tag comment.user.avatar, size: '50x50'
                    - else
                      = link_to user_path(comment.user.id) do
                        .user_icon = image_tag 'default_user.PNG', size: '50x50'
                    .tweet
                      strong = comment.user.name
                      span.custom-user-id= " @" + comment.user.custom_user_id
                      br
                      = comment.content
                      - if comment.image.attached?
                        - if comment.image.length == 1
                          .row
                            .col-md-12
                              .d-flex.tweet_image.mt-2
                                = image_tag comment.image.first, size: '600x400'
                        - else
                          .row
                            - comment.image.each do |image|
                              .col-md-6
                                .d-flex.tweet_image.mt-2
                                  = image_tag image, size: '300x200'
                  .container.pt-2.d-flex.justify-content-between    
                    button.btn-light.mt-2.tweet_form_icon
                      i.bi.bi-chat
                    = render partial: 'retweets/retweet_button', locals: { tweet: @tweet }
                    = render partial: 'favorites/favorite_buttom', locals: { tweet: @tweet }
                    = render partial: 'bookmarks/bookmark_button', locals: { tweet: @tweet }
                    button.btn-light.mt-2.tweet_form_icon
                      i.bi.bi-upload
                      .mt-2
                  .border-bottom
        
      - else
        .container
          .row
            .col-3.border-end.p-0
              .mt-3
                button.btn.btn-light.side_menu
                  | <i class='bi bi-hash'></i>&nbsp;&nbsp;話題を検索
              .mt-3
                button.btn.btn-light.side_menu
                  | <i class="bi bi-gear"></i>&nbsp;&nbsp;設定
            .col-8.main_before_login
              .mt-3.fw-bold
                | Twitterを使ってみよう
              .mt-2.fw-lighter
                | 今すぐ登録して、タイムラインをカスタマイズしましょう。
              .mt-2
                button.btn.btn-outline-dark.main_before_login_button
                  | アカウントを作成

    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"