config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    member do
      get :follows, :followers
    end
    resource :relationships, only: %i[create destroy]
  end

  devise_scope :user do
    get 'users/auth/:provider/callback', to: 'users/omniauth_callbacks#github'
  end

  root to: 'tweets#index'
  resources :tweets do
    collection do
      get 'bookmarks', to: 'tweets#bookmarks'
    end
    resources :comments, only: [:create]
    resource :favorites, only: %i[create destroy]
    resource :retweets, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end

  post '/tweets', to: 'tweets#create'

  resources :rooms

  resources :rooms do
    resources :messages
  end

  resources :notifications, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates :content, presence: true, length: { maximum: 140 }, unless: proc { image.attached? }

  has_many :favorites, dependent: :destroy
  has_many :retweets, dependent: :destroy
  has_many_attached :image

  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private

  def create_notifications
    Notification.create(subject: self, user: tweet.user, action_type: :commented_to_own_tweet)
    NotificationMailer.comment_notification(self).deliver_now
  end
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private

  def create_notifications
    Notification.create(subject: self, user: tweet.user, action_type: :liked_to_own_tweet)
    NotificationMailer.favorite_notification(self).deliver_now
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :subject, polymorphic: true
  belongs_to :user

  enum action_type: { commented_to_own_tweet: 0, liked_to_own_tweet: 1, followed_me: 2, retweeted_to_own_tweet: 3 }
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private

  def create_notifications
    Notification.create(subject: self, user: followed, action_type: :followed_me)
    NotificationMailer.follow_notification(followed, follower).deliver_now
  end
end

app/models/retweet.rb
# frozen_string_literal: true

class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private

  def create_notifications
    Notification.create(subject: self, user: tweet.user, action_type: :retweeted_to_own_tweet)
    NotificationMailer.retweet_notification(self).deliver_now
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/room_user.rb
# frozen_string_literal: true

class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140 }, unless: proc { image.attached? }

  has_many :retweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many_attached :image

  has_one :notification, as: :subject, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def retweeted_by?(user)
    retweets.exists?(user_id: user.id)
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[github]

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true
  validates :uid, uniqueness: { scope: :provider }

  before_create :set_custom_user_id

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.name = auth.info.name
      user.email = auth.info.email || 'default@example.com'
      user.phone_number = auth.info.phone_number || '09012345678'
      user.date_of_birth = auth.info.date_of_birth || '2000-01-01'
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def follow(user)
    follower.create(followed_id: user.id)
  end

  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  has_many :tweets, dependent: :destroy
  has_many :retweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_tweets, through: :bookmarks, source: :tweet
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy, inverse_of: :follower
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy, inverse_of: :followed
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  has_many :messages, dependent: :destroy
  has_one_attached :avatar
  has_one_attached :header
  has_many :notifications, dependent: :destroy

  private

  def set_custom_user_id
    self.custom_user_id = SecureRandom.urlsafe_base64(8)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  def index
    @room = Room.all
    @user = current_user
  end

  def create
    user_ids = params[:user_ids]
    @room = Room.joins(:users)
                .where(users: { id: user_ids })
                .group('rooms.id')
                .having('COUNT(rooms.id) = ?', user_ids.size)
                .first
    if @room.nil?
      @room = Room.new(room_params)
      @room.save
    end
    redirect_to room_messages_path(@room)
  end

  private

  def room_params
    params.permit(user_ids: [])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def hidden_field_tag(_name, _value = nil, _options = {})
    raise 'Happiness chainではhidden_field_tagの使用を禁止しています'
  end
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  FLASH_STYLE = {
    'alert' => 'warning',
    'notice' => 'success',
    'error' => 'danger'
  }.freeze

  def bootstrap_alert(key)
    FLASH_STYLE[key]
  end
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/retweets_helper.rb
# frozen_string_literal: true

module RetweetsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/rooms/index.html.slim
doctype html
html[lang="ja"]
  head
    meta[charset="utf-8"]
    title
      | Twitterクローン
    link href="/assets/message.css" rel="stylesheet"

  body
    = render partial: 'shared/header'    
    .border-top.mt-3
      - if user_signed_in?
        .container
          .row
            .col-2.border-end
              .mt-3
                = button_to root_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-house-door
                  | &nbsp;&nbsp;ホーム
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-hash
                  | &nbsp;&nbsp;話題を検索
              .mt-3
                = button_to notifications_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bell
                  | &nbsp;&nbsp;通知
              .mt-3
                button.btn.btn-light.side_menu
                  strong
                    i.bi.bi-envelope-fill
                    | &nbsp;&nbsp;メッセージ
              .mt-3
                = button_to bookmarks_tweets_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bookmark
                  | &nbsp;&nbsp;ブックマーク
              .mt-3
                = button_to user_path(@user), method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-person
                  | &nbsp;&nbsp;プロフィール
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-three-dots
                  | &nbsp;&nbsp;もっと見る
              .mt-3
                button.btn.btn-primary.col-11.tweet_button
                  | ツイートする
              .side_user_icon
                .d-flex.align-items-center
                  - if current_user.avatar.attached?
                    = image_tag current_user.avatar, size: '50x50'
                  - else
                    = image_tag 'default_user.PNG', size: '50x50'
                  .d-flex.flex-column.side_user_name
                    strong = current_user.name
                    = "@" + current_user.custom_user_id
                
            .col-4.main_before_login.border-end
              - current_user.rooms.each do |room|
                .rooms.d-flex.flex-row.mt-2
                  - another_user = room.users.where.not(id: current_user.id).first
                  .d-flex.align-items-center
                    .avatar
                      - if another_user.avatar.attached? 
                        = link_to user_path(another_user) do
                          .avatar = image_tag another_user.avatar, size: '50x50'
                      - else
                        = link_to user_path(another_user) do
                          .avatar = image_tag 'default_user.PNG', size: '50x50'
                    .room
                      .room-name
                        = link_to another_user.name, room_messages_path(room_id: room.id)
                .border-bottom.mt-2
            .col-6
              h2.fw-bold.text-center
                      | メッセージを選択してください。

    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"




    

app/views/rooms/new.html.slim
doctype html
html[lang="ja"]
  head
    meta[charset="utf-8"]
    title
      | Twitterクローン
    link href="/assets/room.css" rel="stylesheet"

  body
    = render partial: 'shared/header'    
    .border-top.mt-3
      - if user_signed_in?
        .container
          .row
            .col-2
              .mt-3
                = button_to root_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  strong
                    i.bi.bi-house-door-fill
                    | &nbsp;&nbsp;ホーム
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-hash
                  | &nbsp;&nbsp;話題を検索
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-bell
                  | &nbsp;&nbsp;通知
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-envelope
                  | &nbsp;&nbsp;メッセージ
              .mt-3
                = button_to bookmarks_tweets_path, method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-bookmark
                  | &nbsp;&nbsp;ブックマーク
              .mt-3
                = button_to user_path(@user), method: :get, class: "btn btn-light side_menu profile_button" do
                  i.bi.bi-person
                  |  &nbsp;&nbsp;プロフィール
              .mt-3
                button.btn.btn-light.side_menu
                  i.bi.bi-three-dots
                  | &nbsp;&nbsp;もっと見る
              .mt-3
                button.btn.btn-primary.col-11.tweet_button
                  | ツイートする
              .side_user_icon
                .d-flex.align-items-center
                  - if current_user.avatar.attached?
                    = image_tag current_user.avatar, size: '50x50'
                  - else
                    = image_tag 'default_user.PNG', size: '50x50'
                  .d-flex.flex-column.side_user_name
                    strong = current_user.name
                    = "@" + current_user.custom_user_id
                
            .col-4.main_before_login.border-end
              .rooms
                - current_user.rooms.each do |room|
                  .room
                    .room-name
                      - another_user = room.users.where.not(id: current_user.id).first
                      = link_to another_user.name, room_messages_path(room)
                    .delete-room
                      = link_to "×", room_path(room), method: :delete
            .col-4.main_before_login.border-end  


    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"




    